<a href="https://colab.research.google.com/github/cristiancamiloosoriohernandez/Taller-2---Pandas/blob/main/Taller_2_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Misión 1: Importación y Diagnóstico
1.Importa la librería pandas con su alias común pd.

2.Carga el archivo ventas_videojuegos.csv en una variable llamada df_ventas.

3.Muestra las primeras 7 filas del dataset.

4.Imprime la información general (.info()) para conocer las columnas y tipos de datos.

In [ ]:
import pandas as pd
df_ventas = pd.read_csv("/content/ventas_videojuegos.csv")
df_ventas.head(7)

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25
1,2,CyberQuest,Xbox,Norteamerica,50,12
2,3,Galactic Combat,PC,Europa,40,45
3,4,Race King,Nintendo Switch,Asia,30,8
4,5,Fantasy RPG,PS5,Latinoamerica,70,30
5,6,Soccer Stars 2026,Xbox,Europa,60,15
6,7,CyberQuest,PC,Latinoamerica,50,5

In [ ]:
df_ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_Venta           20 non-null     int64
 1   Videojuego         20 non-null     object
 2   Plataforma         20 non-null     object
 3   Region             20 non-null     object
 4   Precio_Unitario    20 non-null     int64
 5   Unidades_Vendidas  20 non-null     int64
dtypes: int64(3), object(3)
memory usage: 1.1+ KB

# Misión 2: Operaciones Vectorizadas
El dataset cuenta con las columnas Precio_Unitario y Unidades_Vendidas.

1.Crea una nueva columna llamada Ingreso_Total calculada a partir de la multiplicación de ambas columnas.

2.Muestra las primeras 5 filas para comprobar que la nueva columna se generó correctamente.

In [ ]:
df_ventas["ingreso_total"] = df_ventas["Precio_Unitario"] * df_ventas["Unidades_Vendidas"]
df_ventas.head(5)

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas,ingreso_total
0,1,Soccer Stars 2026,PS5,Latinoamerica,60,25,1500
1,2,CyberQuest,Xbox,Norteamerica,50,12,600
2,3,Galactic Combat,PC,Europa,40,45,1800
3,4,Race King,Nintendo Switch,Asia,30,8,240
4,5,Fantasy RPG,PS5,Latinoamerica,70,30,2100

# Misión 3: Los Filtros
La gerencia comercial necesita extraer un segmento específico.

1.Filtra el dataframe para obtener únicamente las filas donde la Region sea igual a 'Europa' Y el Ingreso_Total sea mayor a 500.

2.Guarda este resultado en una nueva variable llamada df_europa_top y muéstrala en pantalla.

In [ ]:
c1 = df_ventas["Region"] == "Europa"
c2 = df_ventas["ingreso_total"] > 500
df_europa_top = df_ventas[c1 & c2]
df_europa_top.head()

,ID_Venta,Videojuego,Plataforma,Region,Precio_Unitario,Unidades_Vendidas,ingreso_total
2,3,Galactic Combat,PC,Europa,40,45,1800
5,6,Soccer Stars 2026,Xbox,Europa,60,15,900
12,13,Galactic Combat,PS5,Europa,40,50,2000

# Misión 4: Agrupación y Respuestas de Negocio
Queremos evaluar el rendimiento por consola de videojuegos.

1.Usando el dataframe original (df_ventas), agrupa los datos por la columna Plataforma.

2.Suma las Unidades_Vendidas por cada una.

3.Almacena este resumen en una variable llamada reporte_plataformas y muéstralo en pantalla.

4.Responde en una celda de texto: ¿Cuál es la plataforma o consola con más unidades vendidas en este conjunto de datos?

In [ ]:
reporte_plataformas = df_ventas.groupby("Plataforma")["Unidades_Vendidas"].sum()
reporte_plataformas

Plataforma
Nintendo Switch     56
PC                 103
PS5                151
Xbox                88
Name: Unidades_Vendidas, dtype: int64

en el conjunto de datos vemos que la consola con mayor numero de unidades vendidas es la PS5.

# Misión 5: Entrega de Reporte
Para finalizar, exporta tu objeto reporte_plataformas a un archivo de formato CSV llamado reporte_final_plataformas.csv. ¡Asegúrate de incluir los encabezados!

In [ ]:
reporte_plataformas.to_csv("reporte_final_plataformas.csv", header = True)